###
# @name=POST /directory
POST localhost:8080/api/directory HTTP/1.1

###
GET localhost:8080/api/directory?path=

###
# @name=POST /resource
POST localhost:8080/api/resource?path=papka/ HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file1.mp3"

< C:\file.mp3
--boundary--

###
# @name= GET /resource/download
GET localhost:8080/api/resource/download?path=folder/ HTTP/1.1
